// Define your quotes array
const quotes = [
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
    { text: "Dream it. Wish it. Do it.", author: "Anonymous" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
    { text: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Everything has beauty, but not everyone can see it.", author: "Confucius" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "If you don’t like the road you’re walking, start paving another one.", author: "Dolly Parton" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "The harder you work, the luckier you get.", author: "Gary Player" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy" },
    { text: "A goal is not always meant to be reached, it often serves simply as something to aim at.", author: "Bruce Lee" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
    { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you’ll see obstacles.", author: "Wayne Dyer" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "You can do anything, but not everything.", author: "David Allen" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { text: "The future depends on what we do in the present.", author: "Mahatma Gandhi" },
    { text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { text: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { text: "In the end, it's not the years in your life that count, it's the life in your years.", author: "Abraham Lincoln" },
    { text: "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.", author: "Orison Swett Marden" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Success is not about what you do, but how much you love what you do.", author: "Anonymous" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
    { text: "We become what we think about.", author: "Earl Nightingale" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
    { text: "Don't wait for the perfect moment. Take the moment and make it perfect.", author: "Zoey Sayward" },
    { text: "The only way to have a good day is to start it with a positive attitude.", author: "Anonymous" },
    { text: "If you want to achieve greatness stop asking for permission.", author: "Anonymous" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "I have not failed. I’ve just found 10,000 ways that won’t work.", author: "Thomas Edison" },
    { text: "The road to success is always under construction.", author: "Lily Tomlin" },
    { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
    { text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "There are no limits to what you can accomplish, except the limits you place on your own thinking.", author: "Brian Tracy" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Anonymous" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
    { text: "Your imagination is your preview of life’s coming attractions.", author: "Albert Einstein" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Great things never come from comfort zones.", author: "Anonymous" },
    { text: "If you don’t build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "A dream doesn’t become reality through magic; it takes sweat, determination and hard work.", author: "Colin Powell" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
    { text: "It does not matter how many times you get knocked down, but how many times you get up.", author: "Vince Lombardi" },
    { text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    { text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { text: "You can do anything, but not everything.", author: "David Allen" },
    { text: "If you don’t believe in yourself, who will?", author: "Katrina Bowden" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "Success is a lousy teacher. It seduces smart people into thinking they can’t lose.", author: "Bill Gates" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Anonymous" },
    { text: "Everything you want is on the other side of fear.", author: "Jack Canfield" },
    { text: "Dream it. Wish it. Do it.", author: "Anonymous" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { text: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you’ll see obstacles.", author: "Wayne Dyer" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "Everything has beauty, but not everyone can see it.", author: "Confucius" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou" },
    { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Success is not the absence of failure; it’s the persistence through failure.", author: "Aisha Tyler" },
    { text: "Every accomplishment starts with the decision to try.", author: "Gail Devers" },
    { text: "Stars can't shine without darkness.", author: "D.H. Sidebottom" },
    { text: "The moon is a reminder that even in darkness, there is beauty.", author: "Anonymous" },
    { text: "Let your dreams be your wings.", author: "Anonymous" },
    { text: "Sometimes, the smallest things take up the most room in your heart.", author: "Winnie the Pooh" },
    { text: "The sky is not the limit, it’s only the beginning.", author: "Anonymous" },
    { text: "Chase the moon, catch the stars.", author: "Anonymous" },
    { text: "Whispers of the past echo in the softest of winds.", author: "Anonymous" },
    { text: "Find me where the sky touches the sea.", author: "Anonymous" },
    { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
    { text: "Let your soul catch the wind and drift into a dream.", author: "Anonymous" },
    { text: "Life is a journey, not a destination.", author: "Ralph Waldo Emerson" },
    { text: "The stars are the scars of the universe.", author: "Anonymous" },
    { text: "Dreams are the whispers of the soul.", author: "Anonymous" },
    { text: "And in that moment, I swear we were infinite.", author: "Stephen Chbosky" },
    { text: "Every sunset brings the promise of a new dawn.", author: "Ralph Waldo Emerson" },
    { text: "When you look at the stars, you see the reflection of your own dreams.", author: "Anonymous" },
    { text: "The sun is setting, but the sky is still full of light.", author: "Anonymous" },
    { text: "Let the ocean worry about being perfect.", author: "Anonymous" },
    { text: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
    { text: "Follow your dreams, they know the way.", author: "Anonymous" },
    { text: "You are the sky, everything else is just the weather.", author: "Pema Chodron" },
    { text: "When the moon is in the seventh house, and Jupiter aligns with Mars...", author: "The 5th Dimension" },
    { text: "The horizon leans forward, offering you space to place new steps of change.", author: "Maya Angelou" },
    { text: "Breathe in the moments, breathe out the stress.", author: "Anonymous" },
    { text: "What you seek is seeking you.", author: "Rumi" },
    { text: "The world is full of magic things, patiently waiting for our senses to grow sharper.", author: "W.B. Yeats" },
    { text: "In the depths of the night, we find ourselves in the most serene parts of the world.", author: "Anonymous" },
    { text: "Some beautiful paths can't be discovered without getting lost.", author: "Anonymous" },
    { text: "A sky full of stars, and all I can think about is you.", author: "Anonymous" },
    { text: "The ocean stirs the heart, inspires the imagination, and brings eternal joy to the soul.", author: "Wyland" },
    { text: "Close your eyes, breathe in deeply, and let your mind wander to a place of serenity.", author: "Anonymous" },
    { text: "Every star is a dream that has come true.", author: "Anonymous" },
    { text: "The stars are the streetlights of eternity.", author: "Anonymous" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "The soul knows no bar nor wall.", author: "Anonymous" },
    { text: "The sun will rise, and we will try again.", author: "Anonymous" },
    { text: "Dreams don’t work unless you do.", author: "John C. Maxwell" },
    { text: "The universe is full of magical things, patiently waiting for our wits to grow sharper.", author: "Eden Phillpotts" },
    { text: "Collect beautiful moments like they are stars, and never let them go.", author: "Anonymous" },
    { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
    { text: "There are far better things ahead than any we leave behind.", author: "C.S. Lewis" },
    { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
    { text: "Dreams are real as long as they last.", author: "Cheryl Houston" },
    { text: "The breeze at dawn has secrets to tell you. Don’t go back to sleep.", author: "Rumi" },
    { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
    { text: "There is a crack in everything, that’s how the light gets in.", author: "Leonard Cohen" },
    { text: "Let the adventure begin.", author: "Anonymous" },
    { text: "You may say I’m a dreamer, but I’m not the only one.", author: "John Lennon" },
    { text: "There’s no time to be bored in a world as beautiful as this.", author: "Anonymous" },
    { text: "And when the night is cloudy, there is still a light that shines on me.", author: "The Beatles" },
    { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
    { text: "The ocean’s roar is music to the soul.", author: "Anonymous" },
    { text: "Moonlight drowns out all but the brightest stars.", author: "J.R.R. Tolkien" },
    { text: "Life is a beautiful dream.", author: "Anonymous" },
    { text: "The wild flowers bloom in the silence of the valley.", author: "Anonymous" },
    { text: "Lose yourself in nature and find peace.", author: "Anonymous" },
    { text: "Let the rain kiss you. Let the rain beat upon your head with silver liquid drops.", author: "Langston Hughes" },
    { text: "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.", author: "Rabindranath Tagore" },
    { text: "When everything is chaos, the universe creates stars.", author: "Anonymous" },
    { text: "Stars can't shine without darkness.", author: "Anonymous" },
    { text: "Life is like a dream; we wake up when we die.", author: "Anonymous" },
    { text: "You are a cloud of dreams in the sky of your life.", author: "Anonymous" },
    { text: "Heaven on Earth is found when we take a moment to be still and be grateful.", author: "Anonymous" },
    { text: "When you gaze into the sky, the sky gazes back into you.", author: "Anonymous" },
    { text: "Chasing dreams in a world full of stars.", author: "Anonymous" },
    { text: "Every day is a new beginning, filled with limitless possibilities.", author: "Anonymous" },
    { text: "Dream big, work hard, stay focused, and surround yourself with good people.", author: "Anonymous" },
    { text: "The sky is the daily bread of the eyes.", author: "Ralph Waldo Emerson" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Sometimes you have to create your own sunshine.", author: "Anonymous" },
    { text: "Let the beauty of what you love be what you do.", author: "Rumi" },
    { text: "Find joy in the ordinary.", author: "Anonymous" },
    { text: "When I admire the wonder of a sunset or the beauty of the moon, my soul expands in the worship of the creator.", author: "Mahatma Gandhi" },
    { text: "What if I fall? Oh, but my darling, what if you fly?", author: "Erin Hanson" },
    { text: "A dream is a wish your heart makes.", author: "Walt Disney" },
    { text: "The horizon always looks brighter when you look beyond it.", author: "Anonymous" },
    { text: "At night, the stars wake up to shine for us.", author: "Anonymous" },
    { text: "Catch a falling star and put it in your pocket.", author: "Anonymous" },
    { text: "With every sunset, a new hope rises.", author: "Anonymous" },
    { text: "Like a flower, you must open your heart to the light.", author: "Anonymous" },
    { text: "Dreams are the seeds of the future.", author: "Anonymous" },
    { text: "When the stars align, everything falls into place.", author: "Anonymous" },
    { text: "The world is full of wonder and miracles.", author: "Anonymous" },
    { text: "Let the music of the universe fill your soul.", author: "Anonymous" },
    { text: "Keep your heart open, your mind free, and your spirit wild.", author: "Anonymous" },
    { text: "Like a dream, life is fleeting and beautiful.", author: "Anonymous" },
    { text: "The dream is the truth.", author: "James Douglas Morrison" },
    { text: "It’s the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho" },
    { text: "Embrace the unknown. It’s where dreams come true.", author: "Anonymous" },
    { text: "In dreams, we enter a world that’s entirely our own.", author: "J.K. Rowling" },
    { text: "In the right light, at the right time, everything is extraordinary.", author: "Aaron Rose" },
    { text: "You are a part of the universe, and the universe is a part of you.", author: "Anonymous" },
    { text: "Let the rhythm of the waves calm your soul.", author: "Anonymous" },
    { text: "Your dreams are the roadmaps to your future.", author: "Anonymous" },
    { text: "When the world is silent, the heart can hear the truth.", author: "Anonymous" },
    { text: "The stars in the sky are not as bright as the stars in your soul.", author: "Anonymous" },
    { text: "The world is a canvas, and your dreams are the paint.", author: "Anonymous" },
    { text: "Fall in love with the process of becoming the best version of yourself.", author: "Anonymous" },
    { text: "When you follow your heart, you’ll never be lost.", author: "Anonymous" },
    { text: "The only limit is the one you set yourself.", author: "Anonymous" },
    { text: "Sometimes the smallest things take up the most space in your heart.", author: "Winnie the Pooh" },
    { text: "The moonlight dances across the ocean, whispering secrets to those who listen.", author: "Anonymous" },
    { text: "Your imagination is the only limit to your creativity.", author: "Anonymous" },
    { text: "Let your dreams carry you to places you've never been.", author: "Anonymous" },
    { text: "The night sky is a reflection of the dreams yet to come.", author: "Anonymous" },
    { text: "In the quiet moments, the heart speaks the loudest.", author: "Anonymous" },
    { text: "Dance with the rhythm of your heart, and let the world fade away.", author: "Anonymous" },
    { text: "You are the dream you’ve always been waiting for.", author: "Anonymous" },
    { text: "Find the magic in everyday moments.", author: "Anonymous" },
    { text: "Sometimes, you need to step outside, get some air, and remind yourself who you are.", author: "Anonymous" },
    { text: "There is beauty in every day, if you choose to see it.", author: "Anonymous" },
    { text: "The world is a mirror, reflecting back the energy you put out.", author: "Anonymous" },
    { text: "Find peace in the simplicity of life.", author: "Anonymous" },
    { text: "Stars are the jewels of the night, each one a story waiting to be told.", author: "Anonymous" },
    { text: "Believe in the magic of new beginnings.", author: "Anonymous" },
    { text: "Sometimes the heart sees what is invisible to the eye.", author: "H. Jackson Brown Jr." },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Live your life in a way that makes the stars jealous.", author: "Anonymous" },
    { text: "When you stop chasing the wrong things, you give the right things a chance to catch you.", author: "Lolly Daskal" },
    { text: "The stars are not as far as they seem, they are only reflections of your dreams.", author: "Anonymous" },
    { text: "Every dream is a little adventure that awaits its moment.", author: "Anonymous" },
    { text: "The sun is the day’s whisper, and the moon is the night’s lullaby.", author: "Anonymous" },
    { text: "The night is a gift to those who cherish silence and wonder.", author: "Anonymous" },
    { text: "Don’t wait for the perfect moment, take the moment and make it perfect.", author: "Anonymous" },
    { text: "The waves kiss the shore, and dreams kiss the soul.", author: "Anonymous" },
    { text: "You were born to create something amazing.", author: "Anonymous" },
    { text: "The clouds are whispers of the sky, carrying secrets from the past.", author: "Anonymous" },
    { text: "Trust the timing of your life.", author: "Anonymous" },
    { text: "Life is a journey, not a race.", author: "Anonymous" },
    { text: "Your dreams are the whispers of your soul.", author: "Anonymous" },
    { text: "The universe has a way of guiding you to where you are meant to be.", author: "Anonymous" },
    { text: "Let your soul be your guide.", author: "Anonymous" },
    { text: "You are the author of your own story.", author: "Anonymous" },
    { text: "The night is full of whispers, but the stars speak in silence.", author: "Anonymous" },
    { text: "Even the smallest step forward is a step toward your dream.", author: "Anonymous" },
    { text: "Take a deep breath, and let the world be your playground.", author: "Anonymous" },
    { text: "The sky is an endless canvas, painted with the colors of your dreams.", author: "Anonymous" },
    { text: "Dare to dream, and the world will open its doors.", author: "Anonymous" },
    { text: "Every sunset is a promise of a new dawn.", author: "Anonymous" },
    { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "Wherever you go, go with all your heart.", author: "Confucius" },
    { text: "The sun never sets on your dreams.", author: "Anonymous" },
    { text: "The ocean is a reminder of the vastness of life and the depth of dreams.", author: "Anonymous" },
    { text: "Your heart knows the way, follow it.", author: "Anonymous" },
    { text: "In the stillness of the night, dreams are born.", author: "Anonymous" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "Find beauty in the simplest things, and let it fill your heart.", author: "Anonymous" },
    { text: "In the silence, the universe speaks to those who listen.", author: "Anonymous" },
    { text: "You are the light of your own dreams.", author: "Anonymous" },
    { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
    { text: "A dream without a plan is just a wish.", author: "Anonymous" },
    { text: "Life is a dream, and I am the dreamer.", author: "Anonymous" },
    { text: "Dance in the rain and dream under the stars.", author: "Anonymous" },
    { text: "There is magic in every moment, if you choose to see it.", author: "Anonymous" },
    { text: "The world is a dream, and we are all its dreamers.", author: "Anonymous" },
    { text: "Trust in the magic of new beginnings.", author: "Anonymous" },
    { text: "The universe is filled with stars and dreams waiting to be discovered.", author: "Anonymous" },
    { text: "The quiet whispers of nature carry the secrets of the universe.", author: "Anonymous" },
    { text: "Sometimes the stars align, and dreams become reality.", author: "Anonymous" },
    { text: "What you dream today is the reality of tomorrow.", author: "Anonymous" },
    { text: "Let your heart be the compass that guides you to your dreams.", author: "Anonymous" },
    { text: "The night sky is a tapestry of dreams waiting to be woven.", author: "Anonymous" },
    { text: "Sometimes the quiet moments are the loudest in the heart.", author: "Anonymous" },
    { text: "The beauty of life is found in the unexpected moments.", author: "Anonymous" },
    { text: "The moonlight is a gentle reminder that even in the dark, there is light.", author: "Anonymous" },
    { text: "Your soul knows where it is going; trust its direction.", author: "Anonymous" },
    { text: "Let your dreams be the wings that carry you to new heights.", author: "Anonymous" },
    { text: "Every morning is a fresh start, full of new possibilities.", author: "Anonymous" },
    { text: "The stars are waiting for you to reach them.", author: "Anonymous" },
    { text: "Let the winds of change guide you to where you belong.", author: "Anonymous" },
    { text: "Sometimes, you just have to take the leap and trust that the net will appear.", author: "Anonymous" },
    { text: "In every breath, there’s a world of possibilities.", author: "Anonymous" },
    { text: "Dreams are the whispers of your soul’s desires.", author: "Anonymous" },
    { text: "You are the dream that you have been waiting for.", author: "Anonymous" },
    { text: "Chase the dream, not the competition.", author: "Anonymous" },
    { text: "In the silence, your heart will reveal the path.", author: "Anonymous" },
    { text: "The stars shine brightest when the night is darkest.", author: "Anonymous" },
    { text: "Live your dreams with the passion of a heart set on fire.", author: "Anonymous" },
    { text: "The universe dances with those who dare to dream.", author: "Anonymous" },
    { text: "Like the stars, your dreams are eternal.", author: "Anonymous" },
    { text: "May your dreams be as vast as the ocean and as endless as the sky.", author: "Anonymous" },
    { text: "Wherever your dreams take you, go with love and courage.", author: "Anonymous" },
    { text: "The dream is not what you see while you sleep; it’s what keeps you awake.", author: "Anonymous" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "When you dream, you are free.", author: "Anonymous" }
];

// Get the quote element by ID
const quoteElement = document.getElementById('quote');

// Get the icon element by ID
const icon = document.getElementById('generate-icon');

// Function to fetch a random quote
function fetchQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const quote = quotes[randomIndex];
    quoteElement.textContent = `"${quote.text}" — ${quote.author}`;
}

// Add event listener to the icon to trigger the fetchQuote function when clicked
if (icon) {
    icon.addEventListener('click', fetchQuote);
}

// Add keydown event listener to trigger the fetchQuote function on Enter or Next keys
document.addEventListener("keydown", function(event) {
    // Check if the Enter key or the Next key (ArrowDown / ArrowRight) is pressed
    if (event.key === "Enter" || event.key === "ArrowDown" || event.key === "ArrowRight") {
        icon.click();  // Simulate the click on the icon to fetch a quote
    }
});